import type { CatalogSeed } from '../types';

/**
 * Bundled seed catalog — 180+ varieties grouped by category.
 *
 * Inspired by Johnny's Selected Seeds, Baker Creek, and High Mowing Organic Seeds.
 *
 * Fields:
 *   category        — top-level grouping shown in the plant picker
 *   name            — specific variety / cultivar name
 *   family          — botanical family (used for companion / rotation logic)
 *   spacingInches   — center-to-center (used for plantsPerSqFt density calc)
 *   daysToMaturity  — 0 for perennials (multi-year)
 *
 * IDs of original generic entries are preserved so any existing bed data
 * (slots that reference 'tomato', 'lettuce', etc.) continues to resolve.
 */
export const SEED_CATALOG: CatalogSeed[] = [

  // ════════════════════════════════════════════════════════════
  // TOMATO
  // ════════════════════════════════════════════════════════════

  // --- kept for backward compat with stored slot data ---
  {
    id: 'tomato',
    name: 'Tomato (generic)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 75,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'parsley', 'marigold'],
    antagonistsWith: ['fennel', 'broccoli', 'cabbage', 'cauliflower'],
    successionIntervalDays: 0,
    notes: 'Generic entry — use a specific variety below for better labeling.',
  },
  {
    id: 'tomato-sun-gold',
    name: 'Sun Gold (cherry)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 57,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'parsley', 'marigold'],
    antagonistsWith: ['fennel', 'broccoli', 'cabbage'],
    successionIntervalDays: 0,
    notes: 'Indeterminate. Exceptional sweet flavor. Orange cherry. Prolific and crack-resistant.',
  },
  {
    id: 'tomato-sweet-million',
    name: 'Sweet Million (cherry)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 65,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'marigold'],
    antagonistsWith: ['fennel', 'broccoli'],
    successionIntervalDays: 0,
    notes: 'Indeterminate. Red cherry. Very sweet and productive. Disease resistant.',
  },
  {
    id: 'tomato-black-cherry',
    name: 'Black Cherry',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 64,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Indeterminate. Dark purple-black cherry. Rich complex flavor.',
  },
  {
    id: 'tomato-brandywine',
    name: 'Brandywine (heirloom)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 85,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'parsley'],
    antagonistsWith: ['fennel', 'broccoli'],
    successionIntervalDays: 0,
    notes: 'Indeterminate heirloom. Large pink beefsteak. Widely regarded as best-tasting tomato.',
  },
  {
    id: 'tomato-cherokee-purple',
    name: 'Cherokee Purple (heirloom)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 80,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Indeterminate heirloom. Deep rose/purple beefsteak. Smoky, rich flavor.',
  },
  {
    id: 'tomato-early-girl',
    name: 'Early Girl',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 52,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'marigold'],
    antagonistsWith: ['fennel', 'broccoli'],
    successionIntervalDays: 0,
    notes: 'Indeterminate. Medium red slicing tomato. Great for short seasons.',
  },
  {
    id: 'tomato-celebrity',
    name: 'Celebrity',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 70,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'carrot', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Determinate. Disease-resistant slicing tomato. Reliable producer.',
  },
  {
    id: 'tomato-san-marzano',
    name: 'San Marzano (paste)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 36, daysToMaturity: 78,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'parsley', 'carrot'],
    antagonistsWith: ['fennel', 'broccoli'],
    successionIntervalDays: 0,
    notes: 'Indeterminate. Classic Italian paste tomato. Meaty with few seeds. Excellent for sauce.',
  },
  {
    id: 'tomato-roma',
    name: 'Roma (paste)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 36, daysToMaturity: 76,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'parsley'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Determinate paste tomato. Sets fruit all at once — great for canning.',
  },
  {
    id: 'tomato-mortgage-lifter',
    name: 'Mortgage Lifter (heirloom)',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 30, rowSpacingInches: 48, daysToMaturity: 85,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Indeterminate heirloom. Very large pink beefsteak. Mild and meaty.',
  },
  {
    id: 'tomato-jet-star',
    name: 'Jet Star',
    category: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 24, rowSpacingInches: 36, daysToMaturity: 72,
    needsTrellis: false, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Indeterminate hybrid. Large red slicer. Low acid, crack-resistant.',
  },

  // ════════════════════════════════════════════════════════════
  // PEPPER
  // ════════════════════════════════════════════════════════════

  {
    id: 'pepper',
    name: 'Pepper (generic)',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🫑',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'carrot', 'tomato', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Generic entry — use a specific variety below.',
  },
  {
    id: 'pepper-california-wonder',
    name: 'California Wonder (bell)',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🫑',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'carrot', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Classic large green/red bell. 4-lobed blocky fruit. Standard for stuffing.',
  },
  {
    id: 'pepper-carmen',
    name: 'Carmen (sweet Italian)',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🌶️',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'tomato', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Johnny\'s top-seller. Sweet Italian frying pepper, 6" tapered fruit. Matures red.',
  },
  {
    id: 'pepper-jalapeno',
    name: 'Jalapeño M',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🌶️',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 15, rowSpacingInches: 24, daysToMaturity: 72,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'carrot', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Standard jalapeño. Medium heat (2,500–5,000 SHU). Heavy producer.',
  },
  {
    id: 'pepper-poblano',
    name: 'Poblano',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🌶️',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 65,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Large dark green mild chile. Used fresh or dried (ancho). 1,000–1,500 SHU.',
  },
  {
    id: 'pepper-banana',
    name: 'Sweet Banana',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🫑',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 15, rowSpacingInches: 24, daysToMaturity: 65,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'tomato', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Long waxy yellow sweet pepper. Great for pickling and frying.',
  },
  {
    id: 'pepper-cayenne',
    name: 'Long Red Cayenne',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🌶️',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 15, rowSpacingInches: 24, daysToMaturity: 72,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Hot cayenne. 30,000–50,000 SHU. Good fresh or dried.',
  },
  {
    id: 'pepper-shishito',
    name: 'Shishito',
    category: 'Pepper',
    family: 'Nightshade',
    icon: '🫑',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 15, rowSpacingInches: 24, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['basil', 'tomato'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Trendy Japanese blistering pepper. Mostly mild, 1 in 10 is hot.',
  },

  // ════════════════════════════════════════════════════════════
  // EGGPLANT
  // ════════════════════════════════════════════════════════════

  {
    id: 'eggplant',
    name: 'Eggplant (generic)',
    category: 'Eggplant',
    family: 'Nightshade',
    icon: '🍆',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 30, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'pepper', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Generic entry.',
  },
  {
    id: 'eggplant-black-beauty',
    name: 'Black Beauty',
    category: 'Eggplant',
    family: 'Nightshade',
    icon: '🍆',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 30, daysToMaturity: 74,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'pepper', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Classic large oval black-purple eggplant. Creamy texture.',
  },
  {
    id: 'eggplant-ichiban',
    name: 'Ichiban (Japanese)',
    category: 'Eggplant',
    family: 'Nightshade',
    icon: '🍆',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 30, daysToMaturity: 61,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'pepper', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Slender Japanese type. Tender skin, sweet mild flavor, early.',
  },
  {
    id: 'eggplant-rosa-bianca',
    name: 'Rosa Bianca (Italian)',
    category: 'Eggplant',
    family: 'Nightshade',
    icon: '🍆',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 30, daysToMaturity: 88,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'pepper', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Italian heirloom. Creamy white with lavender blush. Mild, almost no bitterness.',
  },

  // ════════════════════════════════════════════════════════════
  // CUCUMBER
  // ════════════════════════════════════════════════════════════

  {
    id: 'cucumber',
    name: 'Cucumber (generic)',
    category: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 48, daysToMaturity: 55,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['bean', 'pea', 'radish', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Generic entry.',
  },
  {
    id: 'cucumber-marketmore',
    name: 'Marketmore 76',
    category: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 48, daysToMaturity: 68,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['bean', 'radish', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Classic slicing cuke. Dark green 8" fruit. Disease resistant. Great for hot summers.',
  },
  {
    id: 'cucumber-boston-pickling',
    name: 'Boston Pickling',
    category: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 48, daysToMaturity: 58,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['bean', 'radish', 'dill', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Classic pickling variety. Blocky 3–4" fruit. Crisp and warty. Heirloom.',
  },
  {
    id: 'cucumber-persian-mini',
    name: 'Persian Mini',
    category: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 36, daysToMaturity: 50,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['bean', 'radish', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Short seedless snacking cucumber. Thin skin, no bitterness. Pick at 4–5".',
  },
  {
    id: 'cucumber-lemon',
    name: 'Lemon Cucumber',
    category: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 48, daysToMaturity: 65,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['bean', 'radish', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Heirloom. Round yellow fruit resembling a lemon. Very mild and crisp.',
  },
  {
    id: 'cucumber-english',
    name: 'English (greenhouse)',
    category: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 36, daysToMaturity: 58,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['bean', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Long seedless burpless slicing cuke. Thin skin, no peeling needed.',
  },

  // ════════════════════════════════════════════════════════════
  // SUMMER SQUASH & ZUCCHINI
  // ════════════════════════════════════════════════════════════

  {
    id: 'squash',
    name: 'Zucchini (generic)',
    category: 'Summer Squash',
    family: 'Cucurbit',
    icon: '🫛',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Generic entry.',
  },
  {
    id: 'squash-black-beauty',
    name: 'Black Beauty Zucchini',
    category: 'Summer Squash',
    family: 'Cucurbit',
    icon: '🫛',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 49,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Classic dark green zucchini. Harvest at 6–8". Very productive open bush.',
  },
  {
    id: 'squash-costata-romanesco',
    name: 'Costata Romanesco',
    category: 'Summer Squash',
    family: 'Cucurbit',
    icon: '🫛',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 52,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Italian heirloom ribbed zucchini. Superior nutty flavor. Edible blossoms.',
  },
  {
    id: 'squash-yellow-straightneck',
    name: 'Yellow Straightneck',
    category: 'Summer Squash',
    family: 'Cucurbit',
    icon: '🌽',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Classic yellow summer squash. Tender when harvested small.',
  },
  {
    id: 'squash-pattypan',
    name: 'Sunburst Pattypan',
    category: 'Summer Squash',
    family: 'Cucurbit',
    icon: '🫛',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 52,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Yellow scalloped flying-saucer squash. Best at 2–3". Buttery sweet flavor.',
  },

  // ════════════════════════════════════════════════════════════
  // WINTER SQUASH & PUMPKIN
  // ════════════════════════════════════════════════════════════

  {
    id: 'pumpkin',
    name: 'Butternut Squash',
    category: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 48, rowSpacingInches: 60, daysToMaturity: 110,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'bean', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Generic winter squash entry.',
  },
  {
    id: 'squash-waltham-butternut',
    name: 'Waltham Butternut',
    category: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 48, rowSpacingInches: 60, daysToMaturity: 105,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'bean', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Classic butternut. Stores 3+ months. AAS winner. Tan skin, orange flesh.',
  },
  {
    id: 'squash-delicata',
    name: 'Delicata',
    category: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 100,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'bean'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Small oblong striped squash. Sweet potato flavor. Edible thin skin.',
  },
  {
    id: 'squash-acorn',
    name: 'Acorn (Table Queen)',
    category: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 85,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'bean'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Dark green acorn squash. Sweet yellow-orange flesh. Great for stuffing.',
  },
  {
    id: 'squash-sugar-pumpkin',
    name: 'Sugar Pie Pumpkin',
    category: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 48, rowSpacingInches: 60, daysToMaturity: 100,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'bean', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Small 6–8 lb orange pumpkin. Dense sweet flesh ideal for pies.',
  },
  {
    id: 'squash-spaghetti',
    name: 'Spaghetti Squash',
    category: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 48, rowSpacingInches: 60, daysToMaturity: 100,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'bean'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Oblong yellow squash. Flesh separates into pasta-like strands when baked.',
  },

  // ════════════════════════════════════════════════════════════
  // BEAN
  // ════════════════════════════════════════════════════════════

  {
    id: 'bean',
    name: 'Bush Bean (generic)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 18, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'squash', 'marigold'],
    antagonistsWith: ['onion', 'garlic', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Generic entry.',
  },
  {
    id: 'bean-blue-lake',
    name: 'Blue Lake 274 (bush)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 18, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'squash', 'marigold'],
    antagonistsWith: ['onion', 'garlic', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Classic bush green bean. Straight round pods. Sets all at once — great for canning.',
  },
  {
    id: 'bean-kentucky-wonder',
    name: 'Kentucky Wonder (pole)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 6, rowSpacingInches: 24, daysToMaturity: 65,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['carrot', 'cucumber', 'squash'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 0,
    notes: 'Heirloom pole bean. Long flat pods with rich bean flavor. Grows 6–8 ft.',
  },
  {
    id: 'bean-provider',
    name: 'Provider (bush)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 18, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'marigold'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 14,
    notes: 'Early bush bean. Great for cool climates. Reliable even in wet or cold soils.',
  },
  {
    id: 'bean-dragon-tongue',
    name: 'Dragon Tongue (wax)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 18, daysToMaturity: 57,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 14,
    notes: 'Stunning yellow pod with purple streaks (color fades when cooked). Tender and sweet.',
  },
  {
    id: 'bean-scarlet-runner',
    name: 'Scarlet Runner (pole)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 6, rowSpacingInches: 24, daysToMaturity: 70,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['carrot', 'marigold'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 0,
    notes: 'Beautiful red flowers. Ornamental and edible. Great for trellis.',
  },
  {
    id: 'bean-edamame',
    name: 'Edamame (soybean)',
    category: 'Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 6, rowSpacingInches: 18, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['carrot', 'cucumber'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 0,
    notes: 'Fresh soybeans. Harvest when pods are plump but still green.',
  },

  // ════════════════════════════════════════════════════════════
  // PEA
  // ════════════════════════════════════════════════════════════

  {
    id: 'pea',
    name: 'Pea (generic)',
    category: 'Pea',
    family: 'Legume',
    icon: '🟢',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 24, daysToMaturity: 60,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['carrot', 'radish', 'spinach', 'bean'],
    antagonistsWith: ['onion', 'garlic', 'fennel'],
    successionIntervalDays: 14,
    notes: 'Generic entry.',
  },
  {
    id: 'pea-sugar-snap',
    name: 'Sugar Snap',
    category: 'Pea',
    family: 'Legume',
    icon: '🟢',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 24, daysToMaturity: 62,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['carrot', 'radish', 'spinach'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 14,
    notes: 'Eat the whole pod. Very sweet. Classic Johnny\'s variety. Vines to 6 ft.',
  },
  {
    id: 'pea-snow',
    name: 'Oregon Sugar Pod (snow)',
    category: 'Pea',
    family: 'Legume',
    icon: '🟢',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 24, daysToMaturity: 68,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['carrot', 'radish', 'spinach'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 14,
    notes: 'Flat edible-pod snow pea. Sweet. Compact 28" vines. Great for stir-fry.',
  },
  {
    id: 'pea-lincoln',
    name: 'Lincoln (shelling)',
    category: 'Pea',
    family: 'Legume',
    icon: '🟢',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 24, daysToMaturity: 67,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'spinach'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 14,
    notes: 'Heirloom shelling pea. Short bushy plants. Old-fashioned sweet garden pea.',
  },

  // ════════════════════════════════════════════════════════════
  // LETTUCE & SALAD GREENS
  // ════════════════════════════════════════════════════════════

  {
    id: 'lettuce',
    name: 'Lettuce (generic mix)',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 8, rowSpacingInches: 12, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'strawberry', 'chive'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Generic entry. Sow every 2 weeks for continuous harvest.',
  },
  {
    id: 'lettuce-buttercrunch',
    name: 'Buttercrunch',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 8, rowSpacingInches: 12, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'strawberry'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'AAS winner butterhead. Creamy buttery leaves, loose head. Heat-tolerant.',
  },
  {
    id: 'lettuce-romaine',
    name: 'Parris Island Romaine',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 8, rowSpacingInches: 12, daysToMaturity: 68,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'strawberry'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Upright 9" romaine. Crisp ribs, thick leaves. Good heat and bolt tolerance.',
  },
  {
    id: 'lettuce-red-sails',
    name: 'Red Sails (leaf)',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 45,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'strawberry'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'AAS winner red leaf. Wavy frilly red leaves. Slow to bolt.',
  },
  {
    id: 'lettuce-oakleaf',
    name: 'Black-Seeded Simpson (green leaf)',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 44,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'strawberry'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Fast-growing leaf lettuce. Very mild flavor, light green crinkled leaves.',
  },
  {
    id: 'arugula',
    name: 'Arugula (rocket)',
    category: 'Lettuce & Salad Greens',
    family: 'Brassica',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 8, daysToMaturity: 40,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Spicy peppery salad green. Quick-growing. Broadcast sow thickly. Bolt-prone in heat.',
  },
  {
    id: 'endive',
    name: 'Endive / Escarole',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 10, rowSpacingInches: 12, daysToMaturity: 85,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Slightly bitter chicory-family greens. Tie outer leaves to blanch (reduce bitterness).',
  },
  {
    id: 'lettuce-mesclun',
    name: 'Mesclun Mix',
    category: 'Lettuce & Salad Greens',
    family: 'Asteraceae',
    icon: '🥬',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 2, rowSpacingInches: 6, daysToMaturity: 30,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'radish'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 7,
    notes: 'Blend of lettuces, arugula, mustard greens, and chicories. Broadcast sow, cut-and-come-again.',
  },

  // ════════════════════════════════════════════════════════════
  // SPINACH
  // ════════════════════════════════════════════════════════════

  {
    id: 'spinach',
    name: 'Spinach (generic)',
    category: 'Spinach',
    family: 'Amaranth',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 40,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['strawberry', 'pea', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Generic entry.',
  },
  {
    id: 'spinach-bloomsdale',
    name: 'Bloomsdale Long Standing',
    category: 'Spinach',
    family: 'Amaranth',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 48,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['strawberry', 'pea', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Heirloom. Deeply savoyed dark green leaves. Slow to bolt. Rich flavor.',
  },
  {
    id: 'spinach-regiment',
    name: 'Regiment F1',
    category: 'Spinach',
    family: 'Amaranth',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 37,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['strawberry', 'pea', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Smooth-leaf hybrid. Disease-resistant, very upright. Great for baby leaf harvest.',
  },
  {
    id: 'spinach-new-zealand',
    name: 'New Zealand Spinach',
    category: 'Spinach',
    family: 'Tetragoniaceae',
    icon: '🌿',
    indoorStartWeeks: 4, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['strawberry', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Not true spinach but grows in summer heat. Soak seeds before planting.',
  },

  // ════════════════════════════════════════════════════════════
  // KALE & COOKING GREENS
  // ════════════════════════════════════════════════════════════

  {
    id: 'kale',
    name: 'Kale (generic)',
    category: 'Kale & Cooking Greens',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'beet', 'celery', 'cucumber', 'onion'],
    antagonistsWith: ['tomato', 'strawberry', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Generic entry.',
  },
  {
    id: 'kale-lacinato',
    name: 'Lacinato (Dinosaur) Kale',
    category: 'Kale & Cooking Greens',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 62,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'beet', 'onion'],
    antagonistsWith: ['tomato', 'strawberry', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Narrow dark blue-green savoyed leaves. Nutty, sweet flavor. Italian heirloom.',
  },
  {
    id: 'kale-red-russian',
    name: 'Red Russian Kale',
    category: 'Kale & Cooking Greens',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'beet', 'onion'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Flat oak-leaf shape with reddish stems. Tender and sweet, especially after frost.',
  },
  {
    id: 'kale-curly',
    name: 'Winterbor Curly Kale',
    category: 'Kale & Cooking Greens',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'beet', 'onion'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Tightly curled blue-green leaves. Very cold-hardy. Standard curly kale.',
  },
  {
    id: 'chard',
    name: 'Rainbow Swiss Chard',
    category: 'Kale & Cooking Greens',
    family: 'Amaranth',
    icon: '🌈',
    indoorStartWeeks: 4, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 9, rowSpacingInches: 18, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'medium',
    companionsWith: ['bean', 'onion', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Colorful red/yellow/orange/white stems. Mild flavor. Cut outer stalks.',
  },
  {
    id: 'collard',
    name: 'Champion Collard Greens',
    category: 'Kale & Cooking Greens',
    family: 'Brassica',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['bean', 'onion'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Large blue-green leaves. Southern staple. Very cold-hardy and heat-tolerant.',
  },

  // ════════════════════════════════════════════════════════════
  // BRASSICAS (Broccoli / Cauliflower / Cabbage / Brussels)
  // ════════════════════════════════════════════════════════════

  {
    id: 'broccoli',
    name: 'Broccoli (generic)',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 70,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'potato', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Generic entry.',
  },
  {
    id: 'broccoli-di-cicco',
    name: 'Di Cicco (sprouting)',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 48,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'potato', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Italian heirloom. Cut central head, then side shoots for weeks.',
  },
  {
    id: 'broccoli-gypsy',
    name: 'Gypsy F1',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 57,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'potato'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Johnny\'s top hybrid broccoli. Large domed head, adaptable to heat and cold.',
  },
  {
    id: 'broccoli-romanesco',
    name: 'Romanesco',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Stunning fractal green heads. Nutty flavor between broccoli and cauliflower.',
  },
  {
    id: 'cauliflower',
    name: 'Snowball Y Cauliflower',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 70,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Classic white cauliflower. Tie outer leaves over head to keep white (blanching).',
  },
  {
    id: 'cabbage',
    name: 'Stonehead Cabbage (green)',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥬',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 15, rowSpacingInches: 24, daysToMaturity: 67,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'potato', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Compact 3–4 lb tight heads. Crack-resistant. Great for small gardens.',
  },
  {
    id: 'cabbage-red',
    name: 'Ruby Perfection Cabbage (red)',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🔴',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 15, rowSpacingInches: 24, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Firm round red head. Good storage. Resistant to splitting.',
  },
  {
    id: 'brussels-sprouts',
    name: 'Long Island Brussels Sprouts',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 30, daysToMaturity: 90,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['celery', 'onion', 'marigold'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Heirloom. Start early, transplant in June. Harvest after first fall frost for best flavor.',
  },
  {
    id: 'kohlrabi',
    name: 'Kohlrabi (Early White Vienna)',
    category: 'Brassicas',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 4, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 45,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['celery', 'onion', 'beet'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 14,
    notes: 'Pale green swollen stem. Mild sweet flavor like broccoli stem. Harvest at 2–3".',
  },

  // ════════════════════════════════════════════════════════════
  // CARROT
  // ════════════════════════════════════════════════════════════

  {
    id: 'carrot',
    name: 'Carrot (generic)',
    category: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 12, daysToMaturity: 70,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'tomato', 'parsley'],
    antagonistsWith: ['dill', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Generic entry.',
  },
  {
    id: 'carrot-danvers',
    name: 'Danvers 126',
    category: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 12, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'tomato'],
    antagonistsWith: ['dill', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Reliable 6–7" tapering carrot. Tolerates heavy clay. Stores well.',
  },
  {
    id: 'carrot-nantes',
    name: 'Scarlet Nantes',
    category: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 12, daysToMaturity: 68,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'tomato'],
    antagonistsWith: ['dill', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Cylindrical 6" carrot. Very sweet and tender. Classic French type.',
  },
  {
    id: 'carrot-bolero',
    name: 'Bolero F1 (Nantes)',
    category: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 12, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'tomato'],
    antagonistsWith: ['dill', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Johnny\'s best seller. Smooth 7–8" carrot. Stores extremely well over winter.',
  },
  {
    id: 'carrot-purple-haze',
    name: 'Purple Haze F1',
    category: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 12, daysToMaturity: 73,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion'],
    antagonistsWith: ['dill', 'fennel'],
    successionIntervalDays: 21,
    notes: 'AAS winner. Deep purple skin, orange core. High antioxidants. Sweet Nantes type.',
  },
  {
    id: 'carrot-chantenay',
    name: 'Red Cored Chantenay',
    category: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 3, rowSpacingInches: 12, daysToMaturity: 70,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion'],
    antagonistsWith: ['dill', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Short broad 5–6" carrot. Great for shallow or heavy soils. Good for juicing.',
  },

  // ════════════════════════════════════════════════════════════
  // BEET
  // ════════════════════════════════════════════════════════════

  {
    id: 'beet',
    name: 'Beet (generic)',
    category: 'Beet',
    family: 'Amaranth',
    icon: '🟣',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'kale', 'cabbage'],
    antagonistsWith: ['bean', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Generic entry.',
  },
  {
    id: 'beet-detroit-dark-red',
    name: 'Detroit Dark Red',
    category: 'Beet',
    family: 'Amaranth',
    icon: '🟣',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 58,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'kale'],
    antagonistsWith: ['bean', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Classic heirloom. Deep red globe beet. Uniform and sweet. Good for canning.',
  },
  {
    id: 'beet-golden',
    name: 'Touchstone Gold',
    category: 'Beet',
    family: 'Amaranth',
    icon: '🟡',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'kale'],
    antagonistsWith: ['bean', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Yellow-orange beet. Sweet, doesn\'t bleed. Beautiful roasted.',
  },
  {
    id: 'beet-chioggia',
    name: 'Chioggia (candy stripe)',
    category: 'Beet',
    family: 'Amaranth',
    icon: '🟣',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['lettuce', 'onion'],
    antagonistsWith: ['bean', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Italian heirloom. Concentric red-and-white rings when sliced. Mild and sweet.',
  },

  // ════════════════════════════════════════════════════════════
  // RADISH
  // ════════════════════════════════════════════════════════════

  {
    id: 'radish',
    name: 'Radish (generic)',
    category: 'Radish',
    family: 'Brassica',
    icon: '🔴',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 2, rowSpacingInches: 6, daysToMaturity: 25,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'pea', 'lettuce'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 7,
    notes: 'Generic entry. Excellent row marker crop.',
  },
  {
    id: 'radish-cherry-belle',
    name: 'Cherry Belle',
    category: 'Radish',
    family: 'Brassica',
    icon: '🔴',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 2, rowSpacingInches: 6, daysToMaturity: 22,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'pea'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 7,
    notes: 'Classic small round red radish. Crisp and mild. AAS winner.',
  },
  {
    id: 'radish-french-breakfast',
    name: 'French Breakfast',
    category: 'Radish',
    family: 'Brassica',
    icon: '🔴',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 2, rowSpacingInches: 6, daysToMaturity: 25,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'pea'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 7,
    notes: 'Oblong red radish with white tip. Mild flavor. Traditional eaten with butter.',
  },
  {
    id: 'radish-daikon',
    name: 'Daikon (Japanese)',
    category: 'Radish',
    family: 'Brassica',
    icon: '⚪',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Long white Japanese radish, 12–18". Mild. Soil-breaking cover crop when tilled under.',
  },
  {
    id: 'radish-easter-egg',
    name: 'Easter Egg Mix',
    category: 'Radish',
    family: 'Brassica',
    icon: '🌈',
    indoorStartWeeks: 0, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 2, rowSpacingInches: 6, daysToMaturity: 25,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'pea'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 7,
    notes: 'Mix of red, pink, purple, and white radishes. Fun for kids.',
  },

  // ════════════════════════════════════════════════════════════
  // ONION / ALLIUM
  // ════════════════════════════════════════════════════════════

  {
    id: 'onion',
    name: 'Onion (generic)',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🧅',
    indoorStartWeeks: 10, directSowWeeks: -6,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 110,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'tomato', 'lettuce', 'beet'],
    antagonistsWith: ['bean', 'pea', 'sage'],
    successionIntervalDays: 0,
    notes: 'Generic entry.',
  },
  {
    id: 'onion-copra',
    name: 'Copra (yellow storage)',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🧅',
    indoorStartWeeks: 10, directSowWeeks: -6,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 104,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'tomato', 'lettuce'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Top storage onion. Stores 6–12 months. Johnny\'s top seller for years.',
  },
  {
    id: 'onion-red-burgundy',
    name: 'Red Burgundy',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🧅',
    indoorStartWeeks: 10, directSowWeeks: -6,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 4, rowSpacingInches: 12, daysToMaturity: 95,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'tomato', 'lettuce'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Large flat-round red onion. Mild enough to eat fresh. Short-day type.',
  },
  {
    id: 'scallion',
    name: 'Parade Scallion (bunching)',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🌿',
    indoorStartWeeks: 6, directSowWeeks: -4,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 1, rowSpacingInches: 6, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'tomato', 'lettuce'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 14,
    notes: 'Upright white-shanked green onion. Harvest young. Broadcast sow in bands.',
  },
  {
    id: 'leek',
    name: 'Lincoln Leek',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🌿',
    indoorStartWeeks: 10, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 100,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['carrot', 'celery'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Long white shank. Mild flavor. Hill soil around stalks to increase white stem length.',
  },
  {
    id: 'garlic',
    name: 'Garlic (hardneck)',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🧄',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 240,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'pepper', 'carrot', 'rose'],
    antagonistsWith: ['bean', 'pea', 'sage'],
    successionIntervalDays: 0,
    notes: 'Plant cloves in fall, harvest midsummer. Remove scapes to increase bulb size.',
  },
  {
    id: 'shallot',
    name: 'Prisma Shallot',
    category: 'Onion & Allium',
    family: 'Allium',
    icon: '🧅',
    indoorStartWeeks: 10, directSowWeeks: -6,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 100,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'tomato'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'True seed shallot. Coppery skin, mild sweet flavor. Great for storage.',
  },

  // ════════════════════════════════════════════════════════════
  // CORN
  // ════════════════════════════════════════════════════════════

  {
    id: 'corn',
    name: 'Corn (generic)',
    category: 'Corn',
    family: 'Grass',
    icon: '🌽',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 12, rowSpacingInches: 36, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['bean', 'squash', 'cucumber'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 14,
    notes: 'Generic entry.',
  },
  {
    id: 'corn-peaches-cream',
    name: 'Peaches & Cream',
    category: 'Corn',
    family: 'Grass',
    icon: '🌽',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 12, rowSpacingInches: 36, daysToMaturity: 83,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['bean', 'squash', 'cucumber'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 14,
    notes: 'Bicolor sugary-enhanced sweet corn. Great fresh eating.',
  },
  {
    id: 'corn-silver-queen',
    name: 'Silver Queen',
    category: 'Corn',
    family: 'Grass',
    icon: '🌽',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 12, rowSpacingInches: 36, daysToMaturity: 92,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['bean', 'squash'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 14,
    notes: 'Classic white sweet corn. Long season but very sweet.',
  },
  {
    id: 'corn-bodacious',
    name: 'Bodacious',
    category: 'Corn',
    family: 'Grass',
    icon: '🌽',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 12, rowSpacingInches: 36, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['bean', 'squash'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 14,
    notes: 'SE yellow sweet corn. Excellent flavor, wide planting window.',
  },

  // ════════════════════════════════════════════════════════════
  // MELON & WATERMELON
  // ════════════════════════════════════════════════════════════

  {
    id: 'melon',
    name: 'Cantaloupe (generic)',
    category: 'Melon',
    family: 'Cucurbit',
    icon: '🍈',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 72, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'radish', 'marigold'],
    antagonistsWith: ['potato', 'fennel'],
    successionIntervalDays: 0,
    notes: 'Generic entry.',
  },
  {
    id: 'melon-hales-best',
    name: 'Hale\'s Best Jumbo (cantaloupe)',
    category: 'Melon',
    family: 'Cucurbit',
    icon: '🍈',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 72, daysToMaturity: 86,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'radish', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Classic muskmelon. Deeply netted, salmon-orange flesh. Heirloom.',
  },
  {
    id: 'melon-honeydew',
    name: 'Earlidew Honeydew',
    category: 'Melon',
    family: 'Cucurbit',
    icon: '🍈',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 72, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Early honeydew. Smooth creamy skin, sweet green flesh.',
  },
  {
    id: 'watermelon',
    name: 'Sugar Baby (watermelon)',
    category: 'Melon',
    family: 'Cucurbit',
    icon: '🍉',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 72, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'radish', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Icebox watermelon, 8–10 lbs. Good for small gardens. Dark sweet red flesh.',
  },
  {
    id: 'watermelon-crimson-sweet',
    name: 'Crimson Sweet (watermelon)',
    category: 'Melon',
    family: 'Cucurbit',
    icon: '🍉',
    indoorStartWeeks: 3, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 48, rowSpacingInches: 84, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: ['corn', 'marigold'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Large striped oblong, 25 lbs. Classic sweet red flesh. Disease resistant.',
  },

  // ════════════════════════════════════════════════════════════
  // HERBS
  // ════════════════════════════════════════════════════════════

  {
    id: 'basil',
    name: 'Genovese Basil',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 4, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 12, daysToMaturity: 28,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'pepper', 'marigold'],
    antagonistsWith: ['sage', 'fennel'],
    successionIntervalDays: 21,
    notes: 'Classic Italian large-leaf basil. Pinch flowers to keep productive.',
  },
  {
    id: 'basil-thai',
    name: 'Thai Basil',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 4, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 12, daysToMaturity: 35,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'pepper'],
    antagonistsWith: ['sage'],
    successionIntervalDays: 0,
    notes: 'Anise-licorice flavor. Purple stems and flowers. More heat tolerant than Italian.',
  },
  {
    id: 'basil-lemon',
    name: 'Lemon Basil',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 4, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 12, daysToMaturity: 30,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'pepper'],
    antagonistsWith: ['sage'],
    successionIntervalDays: 0,
    notes: 'Bright citrus-lemon scented. Great in fish dishes and teas.',
  },
  {
    id: 'cilantro',
    name: 'Santo Cilantro',
    category: 'Herb',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 6, rowSpacingInches: 6, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'lettuce', 'bean'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 14,
    notes: 'Slow-bolt. Harvest young. Broadcast sow every 2 weeks.',
  },
  {
    id: 'dill',
    name: 'Fernleaf Dill',
    category: 'Herb',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 9, rowSpacingInches: 12, daysToMaturity: 40,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['cucumber', 'lettuce', 'onion'],
    antagonistsWith: ['carrot', 'fennel', 'tomato'],
    successionIntervalDays: 21,
    notes: 'Dwarf dill. Compact 18". Slow to bolt. Leaf harvest first, then seed heads.',
  },
  {
    id: 'parsley',
    name: 'Giant of Italy Parsley',
    category: 'Herb',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 8, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 8, rowSpacingInches: 12, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'carrot', 'asparagus'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Flat-leaf Italian parsley. Stronger flavor than curly. Biennial.',
  },
  {
    id: 'parsley-curly',
    name: 'Curled Parsley',
    category: 'Herb',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 8, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 8, rowSpacingInches: 12, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'carrot'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Classic curly garnish parsley. More decorative than flat-leaf.',
  },
  {
    id: 'chive',
    name: 'Chives',
    category: 'Herb',
    family: 'Allium',
    icon: '🌿',
    indoorStartWeeks: 8, directSowWeeks: -2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'low',
    companionsWith: ['carrot', 'tomato', 'lettuce'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Perennial onion-flavored herb. Snip leaves throughout season. Repels aphids.',
  },
  {
    id: 'oregano',
    name: 'Italian Oregano',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 90,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['tomato', 'pepper', 'basil'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial in zones 5+. Harvest before flowering for strongest flavor.',
  },
  {
    id: 'thyme',
    name: 'Common Thyme',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 12, daysToMaturity: 85,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['tomato', 'eggplant', 'cabbage'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial. Harvest before flowering. Drought-tolerant.',
  },
  {
    id: 'sage',
    name: 'Common Sage',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 18, rowSpacingInches: 24, daysToMaturity: 75,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['cabbage', 'carrot', 'tomato'],
    antagonistsWith: ['basil', 'onion', 'garlic'],
    successionIntervalDays: 0,
    notes: 'Perennial. Silvery aromatic leaves. Deters cabbage moths.',
  },
  {
    id: 'mint',
    name: 'Spearmint',
    category: 'Herb',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 6, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 90,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'partial-sun', heightCategory: 'medium',
    companionsWith: ['cabbage', 'pea', 'tomato'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial. Very invasive — grow in a pot or with root barrier.',
  },
  {
    id: 'fennel',
    name: 'Florence Fennel (bulbing)',
    category: 'Herb',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 80,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: [],
    antagonistsWith: ['tomato', 'pepper', 'bean', 'basil', 'carrot'],
    successionIntervalDays: 0,
    notes: 'Licorice-flavored bulb. Keep isolated — allelopathic to most vegetables.',
  },

  // ════════════════════════════════════════════════════════════
  // COMPANION FLOWERS
  // ════════════════════════════════════════════════════════════

  {
    id: 'marigold',
    name: 'French Marigold',
    category: 'Companion Flower',
    family: 'Asteraceae',
    icon: '🌼',
    indoorStartWeeks: 4, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: true,
    spacingInches: 6, rowSpacingInches: 12, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['tomato', 'pepper', 'bean', 'cucumber'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Repels nematodes, aphids, and whiteflies. Plant throughout the garden.',
  },
  {
    id: 'nasturtium',
    name: 'Nasturtium',
    category: 'Companion Flower',
    family: 'Tropaeolaceae',
    icon: '🌸',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 10, rowSpacingInches: 12, daysToMaturity: 50,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['cucumber', 'squash', 'tomato', 'bean'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Edible flowers and leaves. Trap crop for aphids. Thrives in poor soil.',
  },
  {
    id: 'borage',
    name: 'Borage',
    category: 'Companion Flower',
    family: 'Boraginaceae',
    icon: '💙',
    indoorStartWeeks: 0, directSowWeeks: 2,
    canDirectSow: true, canStartIndoors: false,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 55,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['tomato', 'squash', 'strawberry'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Blue star flowers attract bees. Repels tomato hornworm. Edible flowers.',
  },

  // ════════════════════════════════════════════════════════════
  // PERENNIALS (in-bed placement)
  // ════════════════════════════════════════════════════════════

  {
    id: 'raspberry',
    name: 'Raspberry',
    category: 'Perennial Fruit',
    family: 'Rose',
    icon: '🍇',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: false,
    spacingInches: 24, rowSpacingInches: 48, daysToMaturity: 365,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'tall',
    companionsWith: ['garlic', 'marigold'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial cane fruit. Prune floricanes after fruiting.',
  },
  {
    id: 'blueberry',
    name: 'Blueberry',
    category: 'Perennial Fruit',
    family: 'Heath',
    icon: '🫐',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: false,
    spacingInches: 48, rowSpacingInches: 72, daysToMaturity: 730,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['strawberry'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial shrub. Needs acidic soil pH 4.5–5.5. Plant 2+ varieties.',
  },
  {
    id: 'kiwi-vine',
    name: 'Kiwi Vine (hardy)',
    category: 'Perennial Fruit',
    family: 'Actinidiaceae',
    icon: '🥝',
    indoorStartWeeks: 0, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: false,
    spacingInches: 120, rowSpacingInches: 144, daysToMaturity: 1825,
    needsTrellis: true, needsSupport: true,
    sunNeeds: 'full-sun', heightCategory: 'vine',
    companionsWith: [],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial vine. Needs strong trellis. Produces for decades.',
  },
  {
    id: 'strawberry',
    name: 'Strawberry',
    category: 'Perennial Fruit',
    family: 'Rose',
    icon: '🍓',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 12, rowSpacingInches: 18, daysToMaturity: 60,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'low',
    companionsWith: ['borage', 'lettuce', 'spinach'],
    antagonistsWith: ['fennel', 'cabbage'],
    successionIntervalDays: 0,
    notes: 'Perennial zones 5–8. Renovate beds every 3 years.',
  },
  {
    id: 'rhubarb',
    name: 'Rhubarb',
    category: 'Perennial Fruit',
    family: 'Polygonaceae',
    icon: '🌿',
    indoorStartWeeks: 8, directSowWeeks: 0,
    canDirectSow: false, canStartIndoors: true,
    spacingInches: 36, rowSpacingInches: 48, daysToMaturity: 730,
    needsTrellis: false, needsSupport: false,
    sunNeeds: 'full-sun', heightCategory: 'medium',
    companionsWith: ['garlic', 'rose'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Do not harvest stems first 2 years. Only eat stalks — leaves are toxic.',
  },
];

/** Look up a seed from the catalog by its id. Returns undefined if not found. */
export function findSeed(id: string): CatalogSeed | undefined {
  return SEED_CATALOG.find((s) => s.id === id);
}

/** All unique category names in display order. */
export const SEED_CATEGORIES: string[] = [
  'Tomato', 'Pepper', 'Eggplant',
  'Cucumber', 'Summer Squash', 'Winter Squash',
  'Bean', 'Pea',
  'Lettuce & Salad Greens', 'Spinach', 'Kale & Cooking Greens', 'Brassicas',
  'Carrot', 'Beet', 'Radish',
  'Onion & Allium', 'Corn', 'Melon',
  'Herb', 'Companion Flower', 'Perennial Fruit',
];
