import type { CatalogSeed } from '../types';

/**
 * Bundled seed catalog (~40 common vegetables, herbs, and companion flowers).
 *
 * sunNeeds     — 'full-sun' | 'partial-sun' | 'shade'
 * heightCategory — 'low' (<12"), 'medium' (12–30"), 'tall' (>30"), 'vine'
 *
 * spacing / rowSpacing drive the grid rectangle:
 *   widthCells  = ceil(spacingInches / 12)
 *   lengthCells = ceil(rowSpacingInches / 12)
 */
export const SEED_CATALOG: CatalogSeed[] = [
  // ─── Nightshades ────────────────────────────────────────────
  {
    id: 'tomato',
    name: 'Tomato',
    family: 'Nightshade',
    icon: '🍅',
    indoorStartWeeks: 6,
    directSowWeeks: 0,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 24,
    rowSpacingInches: 36,
    daysToMaturity: 75,
    needsTrellis: false,
    needsSupport: true,
    sunNeeds: 'full-sun',
    heightCategory: 'tall',
    companionsWith: ['basil', 'carrot', 'parsley', 'marigold'],
    antagonistsWith: ['fennel', 'broccoli', 'cabbage', 'cauliflower'],
    successionIntervalDays: 0,
    notes: 'Requires staking or caging. Pinch suckers on indeterminate varieties.',
  },
  {
    id: 'pepper',
    name: 'Pepper',
    family: 'Nightshade',
    icon: '🫑',
    indoorStartWeeks: 8,
    directSowWeeks: 0,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturity: 80,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['basil', 'carrot', 'tomato', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Needs warm soil. Do not transplant until nights stay above 55°F.',
  },
  {
    id: 'eggplant',
    name: 'Eggplant',
    family: 'Nightshade',
    icon: '🍆',
    indoorStartWeeks: 8,
    directSowWeeks: 0,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 30,
    daysToMaturity: 80,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['bean', 'pepper', 'marigold'],
    antagonistsWith: ['fennel'],
    successionIntervalDays: 0,
    notes: 'Needs consistent heat. Transplant only when soil is reliably above 60°F.',
  },
  // ─── Cucurbits ──────────────────────────────────────────────
  {
    id: 'cucumber',
    name: 'Cucumber',
    family: 'Cucurbit',
    icon: '🥒',
    indoorStartWeeks: 3,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 12,
    rowSpacingInches: 36,
    daysToMaturity: 55,
    needsTrellis: true,
    needsSupport: true,
    sunNeeds: 'full-sun',
    heightCategory: 'vine',
    companionsWith: ['bean', 'lettuce', 'pea', 'radish', 'nasturtium'],
    antagonistsWith: ['potato', 'sage'],
    successionIntervalDays: 14,
    notes: 'Train vertically on a trellis to save space. Pick daily to encourage production.',
  },
  {
    id: 'zucchini',
    name: 'Zucchini',
    family: 'Cucurbit',
    icon: '🥬',
    indoorStartWeeks: 3,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 36,
    rowSpacingInches: 48,
    daysToMaturity: 50,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'nasturtium'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Takes up significant space. One or two plants usually yields more than enough.',
  },
  {
    id: 'squash-winter',
    name: 'Winter Squash',
    family: 'Cucurbit',
    icon: '🎃',
    indoorStartWeeks: 3,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 48,
    rowSpacingInches: 72,
    daysToMaturity: 100,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'vine',
    companionsWith: ['corn', 'bean', 'nasturtium'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 0,
    notes: 'Needs a long season. Cure in sun for 2 weeks after harvest for long storage.',
  },
  // ─── Greens / Brassicas ──────────────────────────────────────
  {
    id: 'lettuce',
    name: 'Lettuce',
    family: 'Asteraceae',
    icon: '🥗',
    indoorStartWeeks: 4,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 8,
    rowSpacingInches: 12,
    daysToMaturity: 45,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'low',
    companionsWith: ['carrot', 'radish', 'cucumber', 'onion'],
    antagonistsWith: [],
    successionIntervalDays: 14,
    notes: 'Ideal for succession planting every 2 weeks. Actually benefits from afternoon shade.',
  },
  {
    id: 'spinach',
    name: 'Spinach',
    family: 'Amaranthaceae',
    icon: '🌿',
    indoorStartWeeks: 0,
    directSowWeeks: -6,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 6,
    rowSpacingInches: 12,
    daysToMaturity: 40,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'low',
    companionsWith: ['pea', 'bean', 'strawberry'],
    antagonistsWith: [],
    successionIntervalDays: 14,
    notes: 'Sow as soon as ground can be worked. Bolts in heat; benefits from shade.',
  },
  {
    id: 'kale',
    name: 'Kale',
    family: 'Brassica',
    icon: '🥬',
    indoorStartWeeks: 6,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturity: 60,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'medium',
    companionsWith: ['beet', 'onion', 'cucumber'],
    antagonistsWith: ['tomato', 'bean'],
    successionIntervalDays: 0,
    notes: 'Flavor improves after frost. Harvest outer leaves repeatedly through the season.',
  },
  {
    id: 'broccoli',
    name: 'Broccoli',
    family: 'Brassica',
    icon: '🥦',
    indoorStartWeeks: 6,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturity: 65,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'dill'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Harvest heads before they yellow. Side shoots continue after the main head.',
  },
  {
    id: 'cauliflower',
    name: 'Cauliflower',
    family: 'Brassica',
    icon: '🤍',
    indoorStartWeeks: 6,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturity: 75,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['celery', 'onion', 'bean'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Tie leaves over the forming head when it reaches 2" across for white curds.',
  },
  {
    id: 'cabbage',
    name: 'Cabbage',
    family: 'Brassica',
    icon: '🥬',
    indoorStartWeeks: 6,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturity: 70,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['dill', 'onion', 'celery'],
    antagonistsWith: ['tomato', 'strawberry'],
    successionIntervalDays: 0,
    notes: 'Row cover prevents cabbage worms and aphids.',
  },
  {
    id: 'arugula',
    name: 'Arugula',
    family: 'Brassica',
    icon: '🌿',
    indoorStartWeeks: 0,
    directSowWeeks: -5,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 6,
    rowSpacingInches: 10,
    daysToMaturity: 40,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'low',
    companionsWith: ['lettuce', 'spinach'],
    antagonistsWith: [],
    successionIntervalDays: 14,
    notes: 'Fast cool-weather crop. Shade cloth extends the season in heat.',
  },
  {
    id: 'chard',
    name: 'Swiss Chard',
    family: 'Amaranthaceae',
    icon: '🌈',
    indoorStartWeeks: 4,
    directSowWeeks: -3,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 6,
    rowSpacingInches: 18,
    daysToMaturity: 50,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'medium',
    companionsWith: ['bean', 'cabbage', 'onion'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Harvest outer leaves to keep producing all season.',
  },
  // ─── Root Vegetables ─────────────────────────────────────────
  {
    id: 'carrot',
    name: 'Carrot',
    family: 'Apiaceae',
    icon: '🥕',
    indoorStartWeeks: 0,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 3,
    rowSpacingInches: 12,
    daysToMaturity: 70,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['lettuce', 'onion', 'sage', 'tomato', 'chives'],
    antagonistsWith: ['dill'],
    successionIntervalDays: 21,
    notes: 'Direct sow only. Thin to 3" spacing for best root development.',
  },
  {
    id: 'radish',
    name: 'Radish',
    family: 'Brassica',
    icon: '🔴',
    indoorStartWeeks: 0,
    directSowWeeks: -5,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 2,
    rowSpacingInches: 6,
    daysToMaturity: 25,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['cucumber', 'lettuce', 'pea', 'nasturtium'],
    antagonistsWith: [],
    successionIntervalDays: 7,
    notes: 'Fastest maturing vegetable. Sow every week for continuous harvest.',
  },
  {
    id: 'beet',
    name: 'Beet',
    family: 'Amaranthaceae',
    icon: '🟣',
    indoorStartWeeks: 0,
    directSowWeeks: -4,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 4,
    rowSpacingInches: 12,
    daysToMaturity: 60,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['onion', 'lettuce', 'cabbage', 'kale'],
    antagonistsWith: ['bean'],
    successionIntervalDays: 21,
    notes: 'Both roots and greens are edible. Each seed cluster may sprout 2-3 plants.',
  },
  {
    id: 'potato',
    name: 'Potato',
    family: 'Nightshade',
    icon: '🥔',
    indoorStartWeeks: 0,
    directSowWeeks: -3,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 12,
    rowSpacingInches: 30,
    daysToMaturity: 80,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['bean', 'corn', 'cabbage'],
    antagonistsWith: ['tomato', 'squash-winter', 'cucumber', 'sunflower'],
    successionIntervalDays: 0,
    notes: 'Plant seed potatoes. Hill soil as plants grow for more tubers.',
  },
  // ─── Legumes ─────────────────────────────────────────────────
  {
    id: 'bean',
    name: 'Green Bean',
    family: 'Legume',
    icon: '🫘',
    indoorStartWeeks: 0,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 4,
    rowSpacingInches: 18,
    daysToMaturity: 55,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['carrot', 'cucumber', 'pea', 'squash-winter'],
    antagonistsWith: ['onion', 'garlic', 'beet'],
    successionIntervalDays: 14,
    notes: 'Fixes nitrogen. Do not sow in cold or wet soil—seeds rot easily.',
  },
  {
    id: 'pea',
    name: 'Pea',
    family: 'Legume',
    icon: '🟢',
    indoorStartWeeks: 0,
    directSowWeeks: -5,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 3,
    rowSpacingInches: 24,
    daysToMaturity: 60,
    needsTrellis: true,
    needsSupport: true,
    sunNeeds: 'full-sun',
    heightCategory: 'vine',
    companionsWith: ['carrot', 'corn', 'cucumber', 'radish', 'spinach'],
    antagonistsWith: ['onion', 'garlic'],
    successionIntervalDays: 14,
    notes: 'Sow as soon as soil can be worked. Provide trellis for climbing.',
  },
  // ─── Alliums ─────────────────────────────────────────────────
  {
    id: 'onion',
    name: 'Onion',
    family: 'Allium',
    icon: '🧅',
    indoorStartWeeks: 10,
    directSowWeeks: -6,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 4,
    rowSpacingInches: 12,
    daysToMaturity: 100,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['carrot', 'lettuce', 'beet'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Sets are easiest for beginners. Long-day vs short-day variety matters by latitude.',
  },
  {
    id: 'garlic',
    name: 'Garlic',
    family: 'Allium',
    icon: '🧄',
    indoorStartWeeks: 0,
    directSowWeeks: -30,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 6,
    rowSpacingInches: 12,
    daysToMaturity: 240,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['tomato', 'pepper', 'carrot', 'rose'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Plant cloves in fall (Oct–Nov) for a summer harvest. Cut scapes in June.',
  },
  {
    id: 'chives',
    name: 'Chives',
    family: 'Allium',
    icon: '🌱',
    indoorStartWeeks: 8,
    directSowWeeks: -3,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 6,
    rowSpacingInches: 12,
    daysToMaturity: 90,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['carrot', 'tomato'],
    antagonistsWith: ['bean', 'pea'],
    successionIntervalDays: 0,
    notes: 'Perennial. Divide clumps every 2–3 years. Flowers attract pollinators.',
  },
  // ─── Herbs ───────────────────────────────────────────────────
  {
    id: 'basil',
    name: 'Basil',
    family: 'Lamiaceae',
    icon: '🌱',
    indoorStartWeeks: 6,
    directSowWeeks: 2,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 12,
    rowSpacingInches: 12,
    daysToMaturity: 60,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['tomato', 'pepper'],
    antagonistsWith: ['sage'],
    successionIntervalDays: 21,
    notes: 'Pinch flower heads to keep producing leaves. Plant near tomatoes.',
  },
  {
    id: 'parsley',
    name: 'Parsley',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 10,
    directSowWeeks: -3,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 8,
    rowSpacingInches: 12,
    daysToMaturity: 70,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'low',
    companionsWith: ['tomato', 'carrot', 'asparagus'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Slow to germinate (3+ weeks). Soak seeds overnight to speed germination.',
  },
  {
    id: 'cilantro',
    name: 'Cilantro',
    family: 'Apiaceae',
    icon: '🌿',
    indoorStartWeeks: 0,
    directSowWeeks: -3,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 6,
    rowSpacingInches: 12,
    daysToMaturity: 45,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'low',
    companionsWith: ['spinach', 'bean', 'pea'],
    antagonistsWith: [],
    successionIntervalDays: 14,
    notes: 'Bolts quickly in heat. Sow every 2 weeks for continuous harvest.',
  },
  {
    id: 'dill',
    name: 'Dill',
    family: 'Apiaceae',
    icon: '🌾',
    indoorStartWeeks: 0,
    directSowWeeks: -2,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 8,
    rowSpacingInches: 12,
    daysToMaturity: 45,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['cabbage', 'lettuce', 'cucumber', 'onion'],
    antagonistsWith: ['carrot', 'tomato'],
    successionIntervalDays: 14,
    notes: 'Self-seeds readily. Allow some plants to go to seed for next year.',
  },
  {
    id: 'mint',
    name: 'Mint',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 8,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 24,
    rowSpacingInches: 24,
    daysToMaturity: 90,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'low',
    companionsWith: ['tomato', 'pea', 'cabbage'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Very invasive—best grown in containers. Repels aphids naturally.',
  },
  {
    id: 'thyme',
    name: 'Thyme',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 8,
    directSowWeeks: 1,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 12,
    rowSpacingInches: 12,
    daysToMaturity: 90,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['tomato', 'eggplant', 'potato'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial in zones 5+. Drought-tolerant once established.',
  },
  {
    id: 'sage',
    name: 'Sage',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 8,
    directSowWeeks: 1,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 18,
    rowSpacingInches: 24,
    daysToMaturity: 75,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['rosemary', 'carrot', 'cabbage', 'bean'],
    antagonistsWith: ['cucumber', 'basil'],
    successionIntervalDays: 0,
    notes: 'Perennial in zones 5+. Hard prune in spring to prevent woodiness.',
  },
  {
    id: 'rosemary',
    name: 'Rosemary',
    family: 'Lamiaceae',
    icon: '🌿',
    indoorStartWeeks: 10,
    directSowWeeks: 2,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 24,
    rowSpacingInches: 36,
    daysToMaturity: 85,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'medium',
    companionsWith: ['bean', 'cabbage', 'carrot', 'sage'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Perennial in zones 7+. Very slow from seed—propagation by cutting is easier.',
  },
  // ─── Other ───────────────────────────────────────────────────
  {
    id: 'corn',
    name: 'Corn',
    family: 'Grass',
    icon: '🌽',
    indoorStartWeeks: 0,
    directSowWeeks: 2,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 12,
    rowSpacingInches: 36,
    daysToMaturity: 80,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'tall',
    companionsWith: ['bean', 'squash-winter', 'pea'],
    antagonistsWith: ['tomato'],
    successionIntervalDays: 14,
    notes: 'Plant in blocks (min 4 rows) for wind pollination. Part of the "Three Sisters."',
  },
  {
    id: 'celery',
    name: 'Celery',
    family: 'Apiaceae',
    icon: '🥬',
    indoorStartWeeks: 10,
    directSowWeeks: 0,
    canDirectSow: false,
    canStartIndoors: true,
    spacingInches: 8,
    rowSpacingInches: 24,
    daysToMaturity: 120,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'partial-sun',
    heightCategory: 'medium',
    companionsWith: ['tomato', 'bean', 'cabbage'],
    antagonistsWith: ['carrot'],
    successionIntervalDays: 0,
    notes: 'Needs consistently moist, fertile soil. One of the more demanding crops.',
  },
  // ─── Companion Flowers ───────────────────────────────────────
  {
    id: 'nasturtium',
    name: 'Nasturtium',
    family: 'Tropaeolaceae',
    icon: '🌸',
    indoorStartWeeks: 0,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 10,
    rowSpacingInches: 12,
    daysToMaturity: 55,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['cucumber', 'zucchini', 'tomato', 'radish'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Edible flowers and leaves. Repels aphids, attracts beneficial insects.',
  },
  {
    id: 'marigold',
    name: 'Marigold',
    family: 'Asteraceae',
    icon: '🌼',
    indoorStartWeeks: 6,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: true,
    spacingInches: 8,
    rowSpacingInches: 12,
    daysToMaturity: 50,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'low',
    companionsWith: ['tomato', 'pepper', 'bean', 'cucumber'],
    antagonistsWith: [],
    successionIntervalDays: 0,
    notes: 'Plant throughout garden to deter nematodes and pests.',
  },
  {
    id: 'sunflower',
    name: 'Sunflower',
    family: 'Asteraceae',
    icon: '🌻',
    indoorStartWeeks: 0,
    directSowWeeks: 1,
    canDirectSow: true,
    canStartIndoors: false,
    spacingInches: 24,
    rowSpacingInches: 24,
    daysToMaturity: 80,
    needsTrellis: false,
    needsSupport: false,
    sunNeeds: 'full-sun',
    heightCategory: 'tall',
    companionsWith: ['cucumber', 'corn'],
    antagonistsWith: ['potato'],
    successionIntervalDays: 14,
    notes: 'Plant on the north end of beds so they don\'t shade shorter crops.',
  },
];

/** Look up a seed from the catalog by its id. */
export function findSeed(id: string): CatalogSeed | undefined {
  return SEED_CATALOG.find((s) => s.id === id);
}
