using GardenApp.Api.Data;
using GardenApp.Api.Helpers;
using GardenApp.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace GardenApp.Api.Endpoints;

public static class ActivityEndpoints
{
    public static void MapActivityEndpoints(this WebApplication app, bool requireAuth = false)
    {
        // ── Tasks ──────────────────────────────────────────────
        var tasks = app.MapGroup("/api/tasks").WithTags("Tasks");
        if (requireAuth) tasks.RequireAuthorization("PaidOrAllowed");

        tasks.MapGet("/", async (HttpRequest req, AppDbContext db) =>
        {
            var hid = HouseholdHelper.GetHouseholdId(req);
            return Results.Ok(await db.Tasks
                .Where(t => t.HouseholdId == hid)
                .OrderBy(t => t.Date)
                .ToListAsync());
        });

        tasks.MapPut("/{id}", async (string id, HttpRequest req, TaskRecord dto, AppDbContext db) =>
        {
            var hid    = HouseholdHelper.GetHouseholdId(req);
            var record = await db.Tasks.FindAsync(id);
            if (record is null)
            {
                dto.Id          = id;
                dto.HouseholdId = hid;
                db.Tasks.Add(dto);
            }
            else
            {
                if (record.HouseholdId != hid) return Results.Forbid();

                record.Date            = dto.Date;
                record.Type            = dto.Type;
                record.PlantId         = dto.PlantId;
                record.BedId           = dto.BedId;
                record.SlotId          = dto.SlotId;
                record.Title           = dto.Title;
                record.Description     = dto.Description;
                record.Completed       = dto.Completed;
                record.IsAutoGenerated = dto.IsAutoGenerated;
            }
            await db.SaveChangesAsync();
            return Results.Ok();
        });

        tasks.MapDelete("/{id}", async (string id, HttpRequest req, AppDbContext db) =>
        {
            var hid    = HouseholdHelper.GetHouseholdId(req);
            var record = await db.Tasks.FindAsync(id);
            if (record is null)           return Results.NotFound();
            if (record.HouseholdId != hid) return Results.Forbid();
            db.Tasks.Remove(record);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });

        // Replace all auto-generated tasks for this household in one transaction
        tasks.MapPost("/replace-auto", async (HttpRequest req, TaskRecord[] incoming, AppDbContext db) =>
        {
            var hid = HouseholdHelper.GetHouseholdId(req);

            await db.Database.ExecuteSqlRawAsync(
                "DELETE FROM Tasks WHERE IsAutoGenerated = 1 AND HouseholdId = {0}", hid);

            foreach (var t in incoming)
                t.HouseholdId = hid;

            db.Tasks.AddRange(incoming);
            await db.SaveChangesAsync();
            return Results.Ok();
        });

        // ── Activity Log ───────────────────────────────────────
        var activity = app.MapGroup("/api/activity").WithTags("Activity");
        if (requireAuth) activity.RequireAuthorization("PaidOrAllowed");

        activity.MapGet("/", async (HttpRequest req, AppDbContext db) =>
        {
            var hid = HouseholdHelper.GetHouseholdId(req);
            return Results.Ok(await db.ActivityLogs
                .Where(a => a.HouseholdId == hid)
                .OrderByDescending(a => a.Date)
                .ToListAsync());
        });

        activity.MapPut("/{id}", async (string id, HttpRequest req, ActivityLogRecord dto, AppDbContext db) =>
        {
            var hid    = HouseholdHelper.GetHouseholdId(req);
            var record = await db.ActivityLogs.FindAsync(id);
            if (record is null)
            {
                dto.Id          = id;
                dto.HouseholdId = hid;
                db.ActivityLogs.Add(dto);
            }
            else
            {
                if (record.HouseholdId != hid) return Results.Forbid();

                record.Date        = dto.Date;
                record.BedId       = dto.BedId;
                record.SlotId      = dto.SlotId;
                record.Type        = dto.Type;
                record.Note        = dto.Note;
                record.YieldAmount = dto.YieldAmount;
                record.YieldUnit   = dto.YieldUnit;
            }
            await db.SaveChangesAsync();
            return Results.Ok();
        });

        activity.MapDelete("/{id}", async (string id, HttpRequest req, AppDbContext db) =>
        {
            var hid    = HouseholdHelper.GetHouseholdId(req);
            var record = await db.ActivityLogs.FindAsync(id);
            if (record is null)           return Results.NotFound();
            if (record.HouseholdId != hid) return Results.Forbid();
            db.ActivityLogs.Remove(record);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
