using GardenApp.Api.Data;
using GardenApp.Api.Models;
using Microsoft.EntityFrameworkCore;

namespace GardenApp.Api.Endpoints;

public static class ActivityEndpoints
{
    public static void MapActivityEndpoints(this WebApplication app)
    {
        // ── Tasks ──────────────────────────────────────────────
        var tasks = app.MapGroup("/api/tasks").WithTags("Tasks");

        tasks.MapGet("/", async (AppDbContext db) =>
            Results.Ok(await db.Tasks.OrderBy(t => t.Date).ToListAsync()));

        tasks.MapPut("/{id}", async (string id, TaskRecord dto, AppDbContext db) =>
        {
            var record = await db.Tasks.FindAsync(id);
            if (record is null)
            {
                dto.Id = id;
                db.Tasks.Add(dto);
            }
            else
            {
                record.Date = dto.Date;
                record.Type = dto.Type;
                record.PlantId = dto.PlantId;
                record.BedId = dto.BedId;
                record.SlotId = dto.SlotId;
                record.Title = dto.Title;
                record.Description = dto.Description;
                record.Completed = dto.Completed;
                record.IsAutoGenerated = dto.IsAutoGenerated;
            }
            await db.SaveChangesAsync();
            return Results.Ok();
        });

        tasks.MapDelete("/{id}", async (string id, AppDbContext db) =>
        {
            var record = await db.Tasks.FindAsync(id);
            if (record is null) return Results.NotFound();
            db.Tasks.Remove(record);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });

        // Replace all auto-generated tasks in one transaction
        tasks.MapPost("/replace-auto", async (TaskRecord[] incoming, AppDbContext db) =>
        {
            await db.Database.ExecuteSqlRawAsync(
                "DELETE FROM Tasks WHERE IsAutoGenerated = 1");
            db.Tasks.AddRange(incoming);
            await db.SaveChangesAsync();
            return Results.Ok();
        });

        // ── Activity Log ───────────────────────────────────────
        var activity = app.MapGroup("/api/activity").WithTags("Activity");

        activity.MapGet("/", async (AppDbContext db) =>
            Results.Ok(await db.ActivityLogs.OrderByDescending(a => a.Date).ToListAsync()));

        activity.MapPut("/{id}", async (string id, ActivityLogRecord dto, AppDbContext db) =>
        {
            var record = await db.ActivityLogs.FindAsync(id);
            if (record is null)
            {
                dto.Id = id;
                db.ActivityLogs.Add(dto);
            }
            else
            {
                record.Date = dto.Date;
                record.BedId = dto.BedId;
                record.SlotId = dto.SlotId;
                record.Type = dto.Type;
                record.Note = dto.Note;
            }
            await db.SaveChangesAsync();
            return Results.Ok();
        });

        activity.MapDelete("/{id}", async (string id, AppDbContext db) =>
        {
            var record = await db.ActivityLogs.FindAsync(id);
            if (record is null) return Results.NotFound();
            db.ActivityLogs.Remove(record);
            await db.SaveChangesAsync();
            return Results.NoContent();
        });
    }
}
