import Dexie, { type Table } from 'dexie';
import type { Settings, Garden, UserSeed, Task, ActivityLog, GardenSeason } from '../types';
import type { StorageAdapter } from './StorageAdapter';
import { DEFAULT_SETTINGS } from './StorageAdapter';

// ─── Dexie Schema ─────────────────────────────────────────────

interface SettingsRecord {
  id: 'singleton'; // always one row
  data: Settings;
}

interface GardenRecord {
  id: string;
  data: Garden;
}

class GardenDb extends Dexie {
  settings!: Table<SettingsRecord, string>;
  gardens!: Table<GardenRecord, string>;
  userSeeds!: Table<UserSeed, string>;
  tasks!: Table<Task, string>;
  activityLogs!: Table<ActivityLog, string>;
  seasons!: Table<GardenSeason, string>;

  constructor() {
    super('GardenApp');
    this.version(1).stores({
      settings: 'id',
      gardens: 'id',
      userSeeds: 'id, seedId',
      tasks: 'id, date, completed',
      activityLogs: 'id, date, bedId',
      seasons: 'id, year',
    });
  }
}

const db = new GardenDb();

// ─── Adapter Implementation ───────────────────────────────────

export class LocalAdapter implements StorageAdapter {
  async getSettings(): Promise<Settings> {
    const record = await db.settings.get('singleton');
    return record?.data ?? DEFAULT_SETTINGS;
  }

  async saveSettings(settings: Settings): Promise<void> {
    await db.settings.put({ id: 'singleton', data: settings });
  }

  async getGarden(): Promise<Garden | null> {
    const record = await db.gardens.get('current');
    return record?.data ?? null;
  }

  async saveGarden(garden: Garden): Promise<void> {
    await db.gardens.put({ id: 'current', data: garden });
  }

  async getUserSeeds(): Promise<UserSeed[]> {
    return db.userSeeds.toArray();
  }

  async saveUserSeed(seed: UserSeed): Promise<void> {
    await db.userSeeds.put(seed);
  }

  async deleteUserSeed(id: string): Promise<void> {
    await db.userSeeds.delete(id);
  }

  async getTasks(): Promise<Task[]> {
    return db.tasks.orderBy('date').toArray();
  }

  async saveTask(task: Task): Promise<void> {
    await db.tasks.put(task);
  }

  async deleteTask(id: string): Promise<void> {
    await db.tasks.delete(id);
  }

  async replaceAllTasks(tasks: Task[]): Promise<void> {
    await db.transaction('rw', db.tasks, async () => {
      // Keep custom (user-created) tasks, replace all auto-generated ones
      await db.tasks.filter((t) => t.isAutoGenerated).delete();
      await db.tasks.bulkPut(tasks);
    });
  }

  async getActivityLogs(): Promise<ActivityLog[]> {
    return db.activityLogs.orderBy('date').reverse().toArray();
  }

  async saveActivityLog(log: ActivityLog): Promise<void> {
    await db.activityLogs.put(log);
  }

  async deleteActivityLog(id: string): Promise<void> {
    await db.activityLogs.delete(id);
  }

  async getSeasons(): Promise<GardenSeason[]> {
    return db.seasons.orderBy('year').reverse().toArray();
  }

  async saveSeason(season: GardenSeason): Promise<void> {
    await db.seasons.put(season);
  }
}
