import type { Task } from '../types';
import { TASK_ICONS, TASK_LABELS } from '../utils/plantingSchedule';
import { SEED_CATALOG } from '../catalog/seeds';
import { parseIsoDate } from '../catalog/frostDates';
import { PlantIcon } from './PlantIcon';

interface TaskCardProps {
  task: Task;
  onToggle: (id: string, completed: boolean) => void;
  onDelete?: (id: string) => void;
}

export function TaskCard({ task, onToggle, onDelete }: TaskCardProps) {
  const seed = task.plantId ? SEED_CATALOG.find((s) => s.id === task.plantId) : null;
  const displayDate = parseIsoDate(task.date).toLocaleDateString('en-US', {
    weekday: 'short',
    month: 'short',
    day: 'numeric',
  });

  return (
    <div
      className={`task-card${task.completed ? ' completed' : ''}`}
      onClick={() => onToggle(task.id, !task.completed)}
    >
      <div className={`task-check${task.completed ? ' done' : ''}`} />

      <div className="task-content">
        <div className="task-title">
          {seed && <><PlantIcon seed={seed} />{' '}</>}{task.title}
        </div>
        {task.description && (
          <div className="task-desc">{task.description}</div>
        )}
        <div className="task-date">
          <span className="badge badge-gray">{TASK_LABELS[task.type]}</span>
          {' '}
          <span className="text-muted">{displayDate}</span>
        </div>
      </div>

      <div className="task-type-icon">{TASK_ICONS[task.type]}</div>

      {onDelete && !task.isAutoGenerated && (
        <button
          className="btn btn-ghost btn-sm"
          onClick={(e) => {
            e.stopPropagation();
            onDelete(task.id);
          }}
          title="Delete task"
        >
          ✕
        </button>
      )}
    </div>
  );
}
