import { create } from 'zustand';
import { v4 as uuidv4 } from 'uuid';
import type {
  Settings,
  Garden,
  Bed,
  PlantSlot,
  PlotFeature,
  UserSeed,
  Task,
  ActivityLog,
  GardenSeason,
  ExportBundle,
  SunExposure,
  NorthEdge,
  CatalogSeed,
} from '../types';
import type { StorageAdapter } from '../adapters/StorageAdapter';
import { DEFAULT_SETTINGS } from '../adapters/StorageAdapter';
import { SEED_CATALOG } from '../catalog/seeds';
import { getFrostDateObjects, parseIsoDate } from '../catalog/frostDates';
import { generateAllTasks } from '../utils/plantingSchedule';

// ─── State Shape ──────────────────────────────────────────────

interface GardenState {
  adapter: StorageAdapter | null;
  settings: Settings;
  garden: Garden | null;
  userSeeds: UserSeed[];
  customSeeds: CatalogSeed[];
  tasks: Task[];
  activityLogs: ActivityLog[];
  seasons: GardenSeason[];
  loading: boolean;
  error: string | null;
}

// ─── Actions ─────────────────────────────────────────────────

interface GardenActions {
  init(adapter: StorageAdapter): Promise<void>;

  saveSettings(settings: Settings): Promise<void>;

  saveGarden(garden: Garden): Promise<void>;
  addBed(bed: Bed): Promise<void>;
  updateBed(bed: Bed): Promise<void>;
  deleteBed(bedId: string): Promise<void>;

  placeSlot(bedId: string, slot: Omit<PlantSlot, 'id'>): Promise<void>;
  updateSlot(bedId: string, slot: PlantSlot): Promise<void>;
  removeSlot(bedId: string, slotId: string): Promise<void>;

  completeTask(id: string, completed: boolean): Promise<void>;
  addCustomTask(task: Omit<Task, 'id' | 'isAutoGenerated'>): Promise<void>;
  deleteTask(id: string): Promise<void>;
  regenerateTasks(): Promise<void>;

  addUserSeed(seedId: string): Promise<void>;
  updateUserSeed(seed: UserSeed): Promise<void>;
  removeUserSeed(id: string): Promise<void>;

  /** Custom seed varieties added by the user (not in the built-in catalog). */
  addCustomSeed(seed: CatalogSeed): Promise<void>;
  deleteCustomSeed(id: string): Promise<void>;

  logActivity(log: Omit<ActivityLog, 'id'>): Promise<void>;
  deleteActivityLog(id: string): Promise<void>;

  /** In-ground plot features (perennials, trees, berry bushes, etc.) */
  addPlotFeature(feature: PlotFeature): Promise<void>;
  updatePlotFeature(feature: PlotFeature): Promise<void>;
  removePlotFeature(id: string): Promise<void>;

  /** Save current garden as a season snapshot (with activity log embedded). */
  archiveCurrentSeason(notes?: string): Promise<void>;
  importSeason(season: GardenSeason): Promise<void>;

  /** Export entire app data to a downloadable JSON file. */
  exportToFile(): void;
  /** Import from an ExportBundle JSON file — replaces all local data. */
  importFromFile(bundle: ExportBundle): Promise<void>;
  /**
   * Wipe everything (garden, tasks, activity logs, seeds, seasons) and reset
   * settings to defaults — keeps storage mode so the user doesn't get locked out.
   * Does NOT clear the household ID in localStorage.
   */
  resetAll(): Promise<void>;
}

// ─── Helpers ──────────────────────────────────────────────────

function currentYear(): number {
  return new Date().getFullYear();
}

function emptyGarden(): Garden {
  return { id: uuidv4(), name: 'My Garden', year: currentYear(), beds: [] };
}

function getLastFrostDate(settings: Settings): Date {
  if (settings.lastFrostDate) return parseIsoDate(settings.lastFrostDate);
  if (settings.zipcode) return getFrostDateObjects(settings.zipcode, currentYear()).lastFrost;
  return new Date(currentYear(), 4, 1); // May 1 fallback
}

// ─── Migration ───────────────────────────────────────────────
// Adds defaults for fields introduced after the initial release so that
// data already saved in IndexedDB doesn't crash the new UI.

function migrateGarden(garden: Garden): Garden {
  return {
    ...garden,
    plotFeatures: garden.plotFeatures ?? [],
    beds: garden.beds.map((bed) => ({
      ...bed,
      sunExposure: bed.sunExposure ?? ('full-sun' as SunExposure),
      northEdge:   bed.northEdge   ?? ('top'      as NorthEdge),
      trellisType: bed.trellisType ?? 'none',
      slots: bed.slots.map((slot) => ({
        ...slot,
        // All slots are now 1×1 — collapse any old 2×3 blocks so the grid
        // renders correctly and the planting count is accurate.
        widthCells:    1,
        lengthCells:   1,
        // Recalculate plantsPerSqFt from the catalog in case it's stale.
        plantsPerSqFt: (() => {
          const seed = SEED_CATALOG.find((s) => s.id === slot.plantId);
          if (!seed) return slot.plantsPerSqFt ?? 1;
          return seed.spacingInches < 12
            ? Math.max(1, Math.floor((12 / seed.spacingInches) ** 2))
            : 1;
        })(),
      })),
    })),
  };
}

// ─── Store ───────────────────────────────────────────────────

export const useGardenStore = create<GardenState & GardenActions>((set, get) => ({
  adapter: null,
  settings: DEFAULT_SETTINGS,
  garden: null,
  userSeeds: [],
  customSeeds: [],
  tasks: [],
  activityLogs: [],
  seasons: [],
  loading: false,
  error: null,

  async init(adapter) {
    set({ loading: true, adapter });
    try {
      const [settings, rawGarden, userSeeds, customSeeds, tasks, activityLogs, seasons] = await Promise.all([
        adapter.getSettings(),
        adapter.getGarden(),
        adapter.getUserSeeds(),
        adapter.getCustomSeeds(),
        adapter.getTasks(),
        adapter.getActivityLogs(),
        adapter.getSeasons(),
      ]);

      // Migrate old data that pre-dates sunExposure / northEdge / widthCells / lengthCells fields
      const garden = rawGarden ? migrateGarden(rawGarden) : null;
      // If the garden changed during migration, persist the upgraded version immediately
      if (garden && JSON.stringify(garden) !== JSON.stringify(rawGarden)) {
        await adapter.saveGarden(garden);
      }

      set({ settings, garden, userSeeds, customSeeds, tasks, activityLogs, seasons, loading: false });
    } catch (e) {
      set({ loading: false });
      // Let the caller (App.tsx) handle subscription/auth errors so it can
      // fall back to LocalAdapter. All other errors are stored for display.
      if (e instanceof Error &&
          (e.message === 'SUBSCRIPTION_REQUIRED' || e.message === 'UNAUTHORIZED')) {
        throw e;
      }
      set({ error: String(e) });
    }
  },

  async saveSettings(settings) {
    await get().adapter!.saveSettings(settings);
    set({ settings });
  },

  async saveGarden(garden) {
    await get().adapter!.saveGarden(garden);
    set({ garden });
  },

  async addBed(bed) {
    const { garden, adapter } = get();
    const existing = garden ?? emptyGarden();
    const updated: Garden = { ...existing, beds: [...existing.beds, bed] };
    await adapter!.saveGarden(updated);
    set({ garden: updated });
  },

  async updateBed(bed) {
    const { garden, adapter } = get();
    if (!garden) return;
    const updated: Garden = {
      ...garden,
      beds: garden.beds.map((b) => (b.id === bed.id ? bed : b)),
    };
    await adapter!.saveGarden(updated);
    set({ garden: updated });
  },

  async deleteBed(bedId) {
    const { garden, adapter } = get();
    if (!garden) return;
    const updated: Garden = { ...garden, beds: garden.beds.filter((b) => b.id !== bedId) };
    await adapter!.saveGarden(updated);
    set({ garden: updated });
  },

  async placeSlot(bedId, slotData) {
    const { garden, adapter } = get();
    if (!garden) return;
    const slot: PlantSlot = { ...slotData, id: uuidv4() };
    const updated: Garden = {
      ...garden,
      beds: garden.beds.map((b) =>
        b.id === bedId ? { ...b, slots: [...b.slots, slot] } : b
      ),
    };
    await adapter!.saveGarden(updated);
    set({ garden: updated });
    await get().regenerateTasks();
  },

  async updateSlot(bedId, slot) {
    const { garden, adapter } = get();
    if (!garden) return;
    const updated: Garden = {
      ...garden,
      beds: garden.beds.map((b) =>
        b.id === bedId
          ? { ...b, slots: b.slots.map((s) => (s.id === slot.id ? slot : s)) }
          : b
      ),
    };
    await adapter!.saveGarden(updated);
    set({ garden: updated });
    await get().regenerateTasks();
  },

  async removeSlot(bedId, slotId) {
    const { garden, adapter } = get();
    if (!garden) return;
    const updated: Garden = {
      ...garden,
      beds: garden.beds.map((b) =>
        b.id === bedId ? { ...b, slots: b.slots.filter((s) => s.id !== slotId) } : b
      ),
    };
    await adapter!.saveGarden(updated);
    set({ garden: updated });
    await get().regenerateTasks();
  },

  async completeTask(id, completed) {
    const task = get().tasks.find((t) => t.id === id);
    if (!task) return;
    const updated = { ...task, completed };
    await get().adapter!.saveTask(updated);
    set((s) => ({ tasks: s.tasks.map((t) => (t.id === id ? updated : t)) }));
  },

  async addCustomTask(data) {
    const task: Task = { ...data, id: uuidv4(), isAutoGenerated: false };
    await get().adapter!.saveTask(task);
    set((s) => ({
      tasks: [...s.tasks, task].sort((a, b) => a.date.localeCompare(b.date)),
    }));
  },

  async deleteTask(id) {
    await get().adapter!.deleteTask(id);
    set((s) => ({ tasks: s.tasks.filter((t) => t.id !== id) }));
  },

  async regenerateTasks() {
    const { garden, settings, adapter } = get();
    if (!garden || !adapter) return;
    const lastFrost = getLastFrostDate(settings);
    const seedMap = new Map(SEED_CATALOG.map((s) => [s.id, s]));
    const autoTasks = generateAllTasks(garden.beds, seedMap, lastFrost);
    await adapter.replaceAllTasks(autoTasks);
    const allTasks = await adapter.getTasks();
    set({ tasks: allTasks });
  },

  async addUserSeed(seedId) {
    if (get().userSeeds.find((s) => s.seedId === seedId)) return;
    const seed: UserSeed = { id: uuidv4(), seedId, owned: true, purchaseYear: currentYear(), notes: '' };
    await get().adapter!.saveUserSeed(seed);
    set((s) => ({ userSeeds: [...s.userSeeds, seed] }));
  },

  async updateUserSeed(seed) {
    await get().adapter!.saveUserSeed(seed);
    set((s) => ({ userSeeds: s.userSeeds.map((u) => (u.id === seed.id ? seed : u)) }));
  },

  async removeUserSeed(id) {
    await get().adapter!.deleteUserSeed(id);
    set((s) => ({ userSeeds: s.userSeeds.filter((u) => u.id !== id) }));
  },

  async addCustomSeed(seed) {
    await get().adapter!.saveCustomSeed(seed);
    set((s) => ({
      customSeeds: [...s.customSeeds.filter((c) => c.id !== seed.id), seed],
    }));
  },

  async deleteCustomSeed(id) {
    await get().adapter!.deleteCustomSeed(id);
    set((s) => ({ customSeeds: s.customSeeds.filter((c) => c.id !== id) }));
  },

  async addPlotFeature(feature) {
    const { garden, adapter } = get();
    if (!garden || !adapter) return;
    const updated: Garden = { ...garden, plotFeatures: [...(garden.plotFeatures ?? []), feature] };
    await adapter.saveGarden(updated);
    set({ garden: updated });
  },

  async updatePlotFeature(feature) {
    const { garden, adapter } = get();
    if (!garden || !adapter) return;
    const updated: Garden = {
      ...garden,
      plotFeatures: (garden.plotFeatures ?? []).map((f) => (f.id === feature.id ? feature : f)),
    };
    await adapter.saveGarden(updated);
    set({ garden: updated });
  },

  async removePlotFeature(id) {
    const { garden, adapter } = get();
    if (!garden || !adapter) return;
    const updated: Garden = {
      ...garden,
      plotFeatures: (garden.plotFeatures ?? []).filter((f) => f.id !== id),
    };
    await adapter.saveGarden(updated);
    set({ garden: updated });
  },

  async logActivity(data) {
    const log: ActivityLog = { ...data, id: uuidv4() };
    await get().adapter!.saveActivityLog(log);
    set((s) => ({ activityLogs: [log, ...s.activityLogs] }));
  },

  async deleteActivityLog(id) {
    await get().adapter!.deleteActivityLog(id);
    set((s) => ({ activityLogs: s.activityLogs.filter((l) => l.id !== id) }));
  },

  async archiveCurrentSeason(notes = '') {
    const { garden, activityLogs, adapter } = get();
    if (!garden) return;
    const season: GardenSeason = {
      id: uuidv4(),
      year: garden.year,
      gardenSnapshot: JSON.parse(JSON.stringify(garden)) as Garden,
      activitySnapshot: activityLogs.filter((l) => {
        // Only logs from this calendar year
        return l.date.startsWith(String(garden.year));
      }),
      notes,
      createdAt: new Date().toISOString(),
    };
    await adapter!.saveSeason(season);
    set((s) => ({ seasons: [season, ...s.seasons] }));
  },

  async importSeason(season) {
    const { adapter } = get();
    // Copy bed layout into a new garden for this year, keeping slots so the
    // user can see what was planted and decide what to keep or clear.
    const newGarden: Garden = {
      ...season.gardenSnapshot,
      id: uuidv4(),
      year: currentYear(),
    };
    await adapter!.saveGarden(newGarden);
    set({ garden: newGarden });
    await get().regenerateTasks();
  },

  // ── Export / Import ─────────────────────────────────────

  exportToFile() {
    const { settings, garden, userSeeds, tasks, activityLogs, seasons } = get();
    const bundle: ExportBundle = {
      version: 2,
      exportedAt: new Date().toISOString(),
      settings,
      garden,
      userSeeds,
      tasks,
      activityLogs,
      seasons,
    };
    const blob = new Blob([JSON.stringify(bundle, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `mylivinggarden-${new Date().getFullYear()}-backup.json`;
    a.click();
    URL.revokeObjectURL(url);
  },

  async importFromFile(bundle) {
    const { adapter } = get();
    if (!adapter) return;

    // Validate bundle version
    if (bundle.version !== 2) {
      throw new Error(`Unsupported export version: ${String(bundle.version)}`);
    }

    // Write everything to storage
    await adapter.saveSettings(bundle.settings);
    if (bundle.garden) await adapter.saveGarden(bundle.garden);
    await adapter.replaceAllTasks(bundle.tasks);
    for (const seed of bundle.userSeeds) await adapter.saveUserSeed(seed);
    for (const log of bundle.activityLogs) await adapter.saveActivityLog(log);
    for (const season of bundle.seasons) await adapter.saveSeason(season);

    // Reload state from storage
    const [settings, garden, userSeeds, tasks, activityLogs, seasons] = await Promise.all([
      adapter.getSettings(),
      adapter.getGarden(),
      adapter.getUserSeeds(),
      adapter.getTasks(),
      adapter.getActivityLogs(),
      adapter.getSeasons(),
    ]);
    set({ settings, garden, userSeeds, tasks, activityLogs, seasons });
  },

  async resetAll() {
    const { adapter, settings } = get();
    if (!adapter) return;

    // Wipe all storage-layer data first
    await adapter.resetAll();

    // Restore a minimal valid state — keep storageMode/apiBaseUrl so the
    // user doesn't get locked out of their backend.
    const freshSettings = {
      ...DEFAULT_SETTINGS,
      storageMode: settings.storageMode,
      apiBaseUrl:  settings.apiBaseUrl,
    };
    await adapter.saveSettings(freshSettings);

    const freshGarden: Garden = {
      id: crypto.randomUUID(),
      name: 'My Garden',
      year: new Date().getFullYear(),
      beds: [],
      plotFeatures: [],
    };
    await adapter.saveGarden(freshGarden);

    set({
      settings:     freshSettings,
      garden:       freshGarden,
      userSeeds:    [],
      customSeeds:  [],
      tasks:        [],
      activityLogs: [],
      seasons:      [],
    });
  },
}));
