using System.ComponentModel.DataAnnotations;

namespace GardenApp.Api.Models;

// ─── Settings ─────────────────────────────────────────────────

public class SettingsRecord
{
    [Key]
    public string Id { get; set; } = "singleton";
    public string Zipcode { get; set; } = string.Empty;
    public string? LastFrostDate { get; set; }
    public string? FirstFallFrostDate { get; set; }
    public string StorageMode { get; set; } = "local";
    public string ApiBaseUrl { get; set; } = string.Empty;
    public bool SetupComplete { get; set; }
}

// ─── Garden ───────────────────────────────────────────────────

/// <summary>
/// The garden is stored as a single JSON document (one row per user).
/// The nested bed/slot structure lives inside the JSON blob, mirroring
/// the client-side object graph exactly with no normalization penalty.
/// </summary>
public class GardenRecord
{
    [Key]
    public string Id { get; set; } = "current";
    /// <summary>Full garden JSON serialised from the client type.</summary>
    public string DataJson { get; set; } = "{}";
}

// ─── User Seeds ───────────────────────────────────────────────

public class UserSeedRecord
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string SeedId { get; set; } = string.Empty;
    public bool Owned { get; set; }
    public int PurchaseYear { get; set; }
    public string Notes { get; set; } = string.Empty;
}

// ─── Tasks ────────────────────────────────────────────────────

public class TaskRecord
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Date { get; set; } = string.Empty;
    public string Type { get; set; } = string.Empty;
    public string? PlantId { get; set; }
    public string? BedId { get; set; }
    public string? SlotId { get; set; }
    public string Title { get; set; } = string.Empty;
    public string Description { get; set; } = string.Empty;
    public bool Completed { get; set; }
    public bool IsAutoGenerated { get; set; }
}

// ─── Activity Log ─────────────────────────────────────────────

public class ActivityLogRecord
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public string Date { get; set; } = string.Empty;
    public string? BedId { get; set; }
    public string? SlotId { get; set; }
    public string Type { get; set; } = string.Empty;
    public string Note { get; set; } = string.Empty;
}

// ─── Garden Season ────────────────────────────────────────────

public class GardenSeasonRecord
{
    [Key]
    public string Id { get; set; } = Guid.NewGuid().ToString();
    public int Year { get; set; }
    /// <summary>Full garden snapshot JSON.</summary>
    public string GardenSnapshotJson { get; set; } = "{}";
    public string CreatedAt { get; set; } = DateTime.UtcNow.ToString("o");
}
